### ISSUE TITLE
not available via mvn

### ISSUE THREAD

**Issue by biancashouse** [manolo/gwtquery-gesture-plugin#8]
not found when i do my mvn build.
from the previous issue, i assume it is not ready yet, because it will be released with gquery 2.0 ?

**Comment by manolo** [comment]
It is in maven repo [1], remember that you have to configure your project to have the sonatype snapthots repo

https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/gwtquery/plugins/gestures-plugin/

**Comment by biancashouse** [comment]
Manolo, I figured it out: you have a typo on the artifact name on your usage page for gestures:

instead of

    <artifactId>gesture-plugin</artifactId>

it should be

    <artifactId>gestures-plugin</artifactId>

**Comment by biancashouse** [comment]
Great I now have the gesture plugin as part of my maven build, but you
depend on elemental 2.8, and I'm using gwt 2.7. I didn't even realise there
is a 2.8 early release.

Can it work with the 2.7 version ?

On Mon, Mar 2, 2015 at 3:23 AM, Manuel Carrasco Moñino <
notifications@github.com> wrote:

> It is in maven repo [1], remember that you have to configure your project
> to have the sonatype snapthots repo
>
>
> https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/gwtquery/plugins/gestures-plugin/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manolo/gwtquery-gesture-plugin/issues/8#issuecomment-76607013>
> .
>



-- 
Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse
